BERG
Fix problem introduced by r46153 (BERG) where the generateQueryString routine fails with string out of range when there are no query parameters to encode.  The bug led to this kind of traceback:

org.sakaiproject.portal.api.PortalHandlerException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:886)
    at org.sakaiproject.util.Validator.generateQueryString(Validator.java:976)
    at org.sakaiproject.portal.charon.handlers.PDAHandler.doGet(PDAHandler.java:119)

Whenever the PDA portal displayed a tool.  The fix is to simply return null when there were no parameters to encode.